/**
 * architectData.js — Curated Scientific Knowledge Base for Mission Architect
 * 
 * Defines authentic targets, objectives, observation methods, educational constraints,
 * scientific trade-offs, evidence mappings, and integrity criteria.
 * 
 * SCIENTIFIC HONESTY PRINCIPLE:
 * All values are labeled as REAL DATA, EDUCATIONAL MODEL, or SIMPLIFIED ASSUMPTION.
 * This is an educational mission-design experience, not an operational spacecraft CAD tool.
 */

export const ARCHITECT_TARGETS = {
  MARS: {
    id: 'MARS',
    name: 'MARS // ARES-1',
    category: 'TERRESTRIAL EXPEDITION TARGET',
    distanceAU: 1.524,
    distanceKm: '225,400,000 km (Mean Opposition)',
    lightTimeOneWay: '12.53 minutes',
    lightTimeTwoWay: '25.06 minutes',
    gravityMs2: 3.721,
    gravityEarthG: '0.379 G',
    atmosphere: '95.3% CO2, 2.6% N2, 1.9% Ar (6.1 hPa surface pressure)',
    thermalRange: '140 K to 300 K (-133°C to +27°C)',
    magneticField: 'No global dynamo; localized crustal remanent magnetic fields',
    solarIrradiance: '589 W/m² (43% of Earth solar flux)',
    threePosition: { x: 0, y: 0, z: -25 },
    visualColor: 0xc1440e,
    wireColor: 0xf97316,
    radius3D: 1.8,
    supportedObjectives: ['SEARCH_WATER_ICE', 'STUDY_ATMOSPHERE', 'MAGNETIC_ENVIRONMENT'],
    source: 'NASA JPL Mars Exploration Program & MAVEN / MRO / Mars Express Datasets',
    evidenceCase: 'CASE_05_NAVIGATION',
    phenomenonId: 'SPACECRAFT_NAVIGATION',
    discoveryId: 'DISC_01_ICE_LUNAR', // cross-topic water in solar system
    humanityNote: 'A 25-minute two-way light delay means no human-in-the-loop joystick control; all atmospheric descent and orbital insertions must be fully autonomous.'
  },
  MOON: {
    id: 'MOON',
    name: 'MOON // LUNA-1',
    category: 'SELENOGRAPHIC GATEWAY',
    distanceAU: 0.00257,
    distanceKm: '384,400 km (Mean Semi-Major Axis)',
    lightTimeOneWay: '1.28 seconds',
    lightTimeTwoWay: '2.56 seconds',
    gravityMs2: 1.622,
    gravityEarthG: '0.165 G',
    atmosphere: 'Surface-bound exosphere (He, Ar, Ne ~10⁵ particles/cm³)',
    thermalRange: '100 K to 390 K (40 K in permanently shadowed polar craters)',
    magneticField: 'Negligible crustal patches; directly exposed to solar wind',
    solarIrradiance: '1,361 W/m² (Earth equivalent)',
    threePosition: { x: 0, y: 0, z: -25 },
    visualColor: 0x94a3b8,
    wireColor: 0x38bdf8,
    radius3D: 1.4,
    supportedObjectives: ['SEARCH_WATER_ICE', 'MAGNETIC_ENVIRONMENT'],
    source: 'NASA LRO (Diviner / LAMP) & Chandrayaan-1 Moon Mineralogy Mapper (M³)',
    evidenceCase: 'CASE_04_LOOKBACK_TIME',
    phenomenonId: 'LIGHT_TIME',
    discoveryId: 'DISC_01_ICE_LUNAR',
    humanityNote: '1.28-second signal lag allows near-real-time teleoperation from Earth, serving as humanity’s proving ground for deep-space autonomous infrastructure.'
  },
  EARTH: {
    id: 'EARTH',
    name: 'EARTH // TERRA-1',
    category: 'TERRESTRIAL BENCHMARK',
    distanceAU: 1.0,
    distanceKm: '149,597,870 km (1.000 AU Reference)',
    lightTimeOneWay: '0.00 seconds (Origin)',
    lightTimeTwoWay: '0.00 seconds',
    gravityMs2: 9.807,
    gravityEarthG: '1.000 G',
    atmosphere: '78.1% N2, 20.9% O2, 0.93% Ar, 0.042% CO2 (1013.25 hPa)',
    thermalRange: '184 K to 330 K (Mean 288 K / +15°C)',
    magneticField: 'Active geodynamo: Dipole moment 8.0 × 10²² A·m² (31-60 µT)',
    solarIrradiance: '1,361 W/m² (Solar Constant at 1 AU)',
    threePosition: { x: 0, y: 0, z: -25 },
    visualColor: 0x2563eb,
    wireColor: 0x60a5fa,
    radius3D: 2.2,
    supportedObjectives: ['STUDY_ATMOSPHERE', 'MAGNETIC_ENVIRONMENT'],
    source: 'NASA Earth Science Division, NOAA GOES / JPSS & ESA Sentinel Telemetry',
    evidenceCase: 'CASE_02_STELLAR_SPECTRUM',
    phenomenonId: 'SPACE_WEATHER',
    discoveryId: 'DISC_03_OXYGEN_CYCLE',
    humanityNote: 'The only known world where atmospheric disequilibrium is maintained by active biological photosynthesis over geological timescales.'
  },
  EUROPA: {
    id: 'EUROPA',
    name: 'EUROPA // JOVIAN MOON',
    category: 'ICY OCEAN WORLD',
    distanceAU: 5.204,
    distanceKm: '628,300,000 km (Mean Closest Distance)',
    lightTimeOneWay: '34.93 minutes',
    lightTimeTwoWay: '69.86 minutes',
    gravityMs2: 1.315,
    gravityEarthG: '0.134 G',
    atmosphere: 'Extremely thin O2 exosphere created by radiolysis of surface water ice',
    thermalRange: '50 K to 125 K (Mean 102 K)',
    magneticField: 'Induced magnetic dipole generated by saline subsurface ocean rotating through Jupiter field',
    solarIrradiance: '50.3 W/m² (3.7% of Earth solar flux; requires RTG or colossal solar wings)',
    threePosition: { x: 0, y: 0, z: -25 },
    visualColor: 0xe0f2fe,
    wireColor: 0x38bdf8,
    radius3D: 1.5,
    supportedObjectives: ['SEARCH_WATER_ICE', 'MAGNETIC_ENVIRONMENT'],
    source: 'NASA Galileo, Juno, Hubble STIS Plume Observations & Europa Clipper Mission Plan',
    evidenceCase: 'CASE_01_EXOPLANET',
    phenomenonId: 'COSMIC_SCALE',
    discoveryId: 'DISC_02_OCEAN_WORLDS',
    humanityNote: 'Europa harbors twice the volume of all Earth’s oceans combined, sheltered beneath 15–25 km of ice, testing our definition of circumstellar habitable zones.'
  },
  TRAPPIST_1E: {
    id: 'TRAPPIST_1E',
    name: 'TRAPPIST-1e // HABITABLE ZONE EXOPLANET',
    category: 'EXTRASOLAR TERRESTRIAL ANALOG',
    distanceAU: 2504000,
    distanceKm: '374,600,000,000,000 km (39.6 Light Years)',
    lightTimeOneWay: '39.6 years',
    lightTimeTwoWay: '79.2 years',
    gravityMs2: 9.12,
    gravityEarthG: '0.930 G (Radius 0.92 R_Earth, Mass 0.692 M_Earth)',
    atmosphere: 'Constrained by JWST NIRSpec/MIRI: Secondary CO2/H2O atmosphere under investigation',
    thermalRange: 'Estimated Equilibrium 246 K (-27°C)',
    magneticField: 'Unknown; subject to intense flare activity from host ultracool M-dwarf',
    solarIrradiance: '900 W/m² (66% of Earth flux, shifted heavily into near-infrared)',
    threePosition: { x: 0, y: 0, z: -25 },
    visualColor: 0x0ea5e9,
    wireColor: 0x0284c7,
    radius3D: 1.7,
    supportedObjectives: ['STUDY_ATMOSPHERE', 'EXOPLANET_BIOSIGNATURE'],
    source: 'NASA Exoplanet Archive, Gillon et al. (Nature 2017) & JWST Transmission Spectra',
    evidenceCase: 'CASE_01_EXOPLANET',
    phenomenonId: 'EXOPLANET_DETECTION',
    discoveryId: 'DISC_05_TRAPPIST_DISCOVERY',
    humanityNote: 'Communicating with a probe at TRAPPIST-1e would require 80 years per ping, transforming space exploration from operational control into an intergenerational gift.'
  },
  PARKER_SUN: {
    id: 'PARKER_SUN',
    name: 'THE SUN // HELIOSPHERIC CORONA',
    category: 'STELLAR PLASMA FURNACE',
    distanceAU: 0.046, // Perihelion of Parker Solar Probe
    distanceKm: '6,900,000 km (Parker Solar Probe Closest Perihelion)',
    lightTimeOneWay: '23.0 seconds',
    lightTimeTwoWay: '46.0 seconds',
    gravityMs2: 274.0,
    gravityEarthG: '27.9 G',
    atmosphere: 'Solar corona: Million-degree ionized Hydrogen/Helium plasma expanding at 400-800 km/s',
    thermalRange: 'Photosphere 5,778 K; Corona 1,000,000 K to 3,000,000 K',
    magneticField: 'Complex multipolar magnetic canopy; Parker spiral and coronal mass ejections',
    solarIrradiance: '650,000 W/m² (Extreme thermal load: Carbon-composite heat shield required)',
    threePosition: { x: 0, y: 0, z: -25 },
    visualColor: 0xf59e0b,
    wireColor: 0xfbbf24,
    radius3D: 2.8,
    supportedObjectives: ['MAGNETIC_ENVIRONMENT', 'SOLAR_CORONA_WIND'],
    source: 'NASA Parker Solar Probe, SOHO, SDO & SWEAP / FIELDS Instrument Suites',
    evidenceCase: 'CASE_02_STELLAR_SPECTRUM',
    phenomenonId: 'SPECTRUM_LAB',
    discoveryId: 'DISC_04_SOLAR_CYCLE',
    humanityNote: 'Directly touching the stellar envelope explains the space weather events that can disable global power grids and satellite constellations on Earth.'
  },
  SAGITTARIUS_A: {
    id: 'SAGITTARIUS_A',
    name: 'SAGITTARIUS A* // GALACTIC SINGULARITY',
    category: 'SUPERMASSIVE COMPACT METRIC',
    distanceAU: 1644000000,
    distanceKm: '2.46 × 10¹⁷ km (26,000 Light Years)',
    lightTimeOneWay: '26,000 years',
    lightTimeTwoWay: '52,000 years',
    gravityMs2: 1e9,
    gravityEarthG: 'Relativistic Metric Curvature (Mass 4.154 × 10⁶ M_Sun)',
    atmosphere: 'Relativistic accretion flow, synchrotron emission & magnetized electron plasma',
    thermalRange: 'Event Horizon: 10⁻¹⁴ K Hawking Temp; Accretion Disk: 10⁹ K relativistic plasma',
    magneticField: 'Dynamically ordered poloidal magnetic field observed via EHT linear polarization',
    solarIrradiance: 'High-energy X-ray / Gamma-ray flares; negligible visible solar flux',
    threePosition: { x: 0, y: 0, z: -25 },
    visualColor: 0x111827,
    wireColor: 0xf97316,
    radius3D: 2.5,
    supportedObjectives: ['RELATIVISTIC_METRIC'],
    source: 'Event Horizon Telescope (EHT Collaboration 2022) & ESO GRAVITY / S2 Astrometry',
    evidenceCase: 'CASE_03_BLACK_HOLE',
    phenomenonId: 'GRAVITY_FIELD',
    discoveryId: 'DISC_06_BLACK_HOLES',
    humanityNote: 'Testing Einstein’s General Relativity in the strongest gravitational well of our galaxy, where space and time swap physical coordinate roles.'
  }
};

export const ARCHITECT_OBJECTIVES = {
  SEARCH_WATER_ICE: {
    id: 'SEARCH_WATER_ICE',
    name: 'SEARCH FOR WATER & ICE RESERVOIRS',
    kicker: 'VOLATILES & HABITABILITY',
    description: 'Map subsurface dielectric interfaces, polar cold traps, and volatile deposits to constrain planetary volatile evolution and in-situ resource availability.',
    primaryQuestion: 'Does the target preserve accessible water ice reservoirs beneath its surface or in permanently shadowed thermal sinks?',
    compatibleMethods: ['RADAR_SOUNDING', 'SPECTROSCOPY_HIGH_RES', 'MULTISPECTRAL_IMAGING'],
    validTargets: ['MARS', 'MOON', 'EUROPA'],
    keyScientificMetric: 'Dielectric Constant (ε_r) & 1.5 µm / 2.0 µm H2O Absorption Bands',
    source: 'NASA Planetary Science Decadal Survey / Volatiles Theme'
  },
  STUDY_ATMOSPHERE: {
    id: 'STUDY_ATMOSPHERE',
    name: 'CHARACTERIZE ATMOSPHERE & ESCAPE PROCESSES',
    kicker: 'PLANETARY CLIMATE & AERONOMY',
    description: 'Measure atmospheric vertical scale height, trace photochemical gas abundances, and quantify thermal versus non-thermal ion atmospheric escape.',
    primaryQuestion: 'What chemical species constitute the atmosphere, and how does solar radiation drive atmospheric dissipation over time?',
    compatibleMethods: ['SPECTROSCOPY_HIGH_RES', 'TRANSIT_PHOTOMETRY', 'IN_SITU_MAGNETOMETRY'],
    validTargets: ['MARS', 'EARTH', 'TRAPPIST_1E'],
    keyScientificMetric: 'Transmission Absorption Depth ΔF/F & Ion Pick-Up Flux',
    source: 'MAVEN Aeronomy Findings & JWST Exoplanet Transmissions'
  },
  MAGNETIC_ENVIRONMENT: {
    id: 'MAGNETIC_ENVIRONMENT',
    name: 'MAP MAGNETOSPHERE, BOW SHOCK & SPACE WEATHER',
    kicker: 'HELIOPHYSICAL SHIELDING',
    description: 'Resolve the topology of magnetic field lines, dayside bow shock compression stand-off distance, and energetic particle precipitation curtains.',
    primaryQuestion: 'How does the solar wind plasma stream interact with the target’s intrinsic, induced, or remnant magnetic fields?',
    compatibleMethods: ['IN_SITU_MAGNETOMETRY', 'MULTISPECTRAL_IMAGING', 'RADAR_SOUNDING'],
    validTargets: ['MARS', 'MOON', 'EARTH', 'EUROPA', 'PARKER_SUN'],
    keyScientificMetric: 'Magnetic Vector Field B (nT) & Plasma Dynamic Pressure (nPa)',
    source: 'NOAA Space Weather Prediction Center & NASA Heliophysics Fleet'
  },
  EXOPLANET_BIOSIGNATURE: {
    id: 'EXOPLANET_BIOSIGNATURE',
    name: 'SEARCH FOR CHEMICAL DISEQUILIBRIUM & BIOSIGNATURES',
    kicker: 'ASTROBIOLOGY & COMPARATIVE PLANETOLOGY',
    description: 'Detect simultaneous presence of reducing (CH4) and oxidizing (O2/O3/CO2) chemical species in an exoplanetary atmosphere that cannot co-exist in thermodynamic equilibrium.',
    primaryQuestion: 'Does the exoplanet atmosphere exhibit anomalous chemical ratios that point to biological metabolic fluxes or abiotic false positives?',
    compatibleMethods: ['SPECTROSCOPY_HIGH_RES', 'TRANSIT_PHOTOMETRY'],
    validTargets: ['TRAPPIST_1E'],
    keyScientificMetric: 'Atmospheric Transmission Absorption Cross-Sections (ppm)',
    source: 'Seager et al. Biosignature Framework & JWST Exoplanet Science'
  },
  RELATIVISTIC_METRIC: {
    id: 'RELATIVISTIC_METRIC',
    name: 'MEASURE SPACETIME CURVATURE & GEODESIC DEFLECTION',
    kicker: 'GENERAL RELATIVITY & GRAVITATIONAL LENSING',
    description: 'Observe the deflection of photon geodesics and the orbital precession of relativistic stellar orbits within the strong gravitational metric of a supermassive black hole.',
    primaryQuestion: 'Do photon trajectories and periastron precession obey exact Einstein Kerr/Schwarzschild solutions at relativistic velocities?',
    compatibleMethods: ['ASTROMETRIC_DEFLECTION', 'SPECTROSCOPY_HIGH_RES'],
    validTargets: ['SAGITTARIUS_A'],
    keyScientificMetric: 'Gravitational Redshift z_g & Relativistic Precession (arcmin/yr)',
    source: 'Einstein Field Equations (1915) & EHT Sgr A* Collaboration (2022)'
  },
  SOLAR_CORONA_WIND: {
    id: 'SOLAR_CORONA_WIND',
    name: 'INVESTIGATE CORONAL HEATING & SOLAR WIND ACCELERATION',
    kicker: 'STELLAR PLASMA & ALFVEN WAVES',
    description: 'Directly sample the sub-Alfvénic corona to identify whether magnetic reconnection switchbacks and ion cyclotron waves drive extreme coronal heating.',
    primaryQuestion: 'Why is the solar corona hundreds of times hotter than the underlying solar photosphere?',
    compatibleMethods: ['IN_SITU_MAGNETOMETRY', 'SPECTROSCOPY_HIGH_RES'],
    validTargets: ['PARKER_SUN'],
    keyScientificMetric: 'Alfvénic Switchback Angle & Ion Temperature Anisotropy (T_perp / T_para)',
    source: 'NASA Parker Solar Probe / FIELDS & SWEAP Collaborations'
  }
};

export const ARCHITECT_METHODS = {
  SPECTROSCOPY_HIGH_RES: {
    id: 'SPECTROSCOPY_HIGH_RES',
    name: 'HIGH-RESOLUTION DISPERSION SPECTROSCOPY',
    kicker: 'QUANTIZED ATOMIC ABSORPTION & EMISSION',
    instrumentType: 'Echelle Spectrograph / NIRSpec Grating Array',
    spectralBand: 'Ultraviolet through Near-Infrared (0.2 µm – 5.0 µm)',
    physicsPrinciple: 'Quantum energy transitions of electrons in atoms and molecules produce unique spectral absorption notches in dispersed starlight.',
    realWorldAnalogs: 'JWST NIRSpec, Keck HIRES, Hubble STIS',
    scienceMerit: 'High: Unambiguously pinpoints specific molecular species (H2O, CO2, CH4, O3) and measures Doppler radial velocity.',
    dataRate: 'Medium to High (50 – 200 MB per observation run)',
    operationalComplexity: 'Requires precise line-of-sight stabilization and long integration times to achieve high signal-to-noise.',
    supportedObjectives: ['STUDY_ATMOSPHERE', 'EXOPLANET_BIOSIGNATURE', 'SEARCH_WATER_ICE', 'RELATIVISTIC_METRIC', 'SOLAR_CORONA_WIND'],
    threeVisualization: 'SPECTRAL_DISPERSION_FAN',
    evidenceLink: 'CASE_02_STELLAR_SPECTRUM',
    phenomenonLink: 'SPECTRUM_LAB'
  },
  TRANSIT_PHOTOMETRY: {
    id: 'TRANSIT_PHOTOMETRY',
    name: 'ULTRA-PRECISE TRANSIT PHOTOMETRY',
    kicker: 'STELLAR FLUX OCCULTATION MONITORING',
    instrumentType: 'Diffraction-Limited Optical / IR Photometer Array',
    spectralBand: 'Broadband Optical & Infrared (0.4 µm – 1.6 µm)',
    physicsPrinciple: 'An opaque body transiting in front of a star blocks starlight proportional to (R_p / R_star)², yielding exact planetary radius and orbital period.',
    realWorldAnalogs: 'NASA Kepler, TESS, ESA CHEOPS & PLATO',
    scienceMerit: 'Very High for geometry: Directly delivers planetary radius, transit timing variations (TTVs), and atmospheric scale height.',
    dataRate: 'Moderate (Continuous 2-minute cadence brightness measurements)',
    operationalComplexity: 'Requires milli-magnitude photometric stability and continuous line-of-sight over entire transit durations.',
    supportedObjectives: ['STUDY_ATMOSPHERE', 'EXOPLANET_BIOSIGNATURE'],
    threeVisualization: 'PHOTOMETRIC_COLLIMATOR_CYLINDER',
    evidenceLink: 'CASE_01_EXOPLANET',
    phenomenonLink: 'EXOPLANET_DETECTION'
  },
  RADAR_SOUNDING: {
    id: 'RADAR_SOUNDING',
    name: 'SUBSURFACE GROUND-PENETRATING RADAR',
    kicker: 'RADIO DIELECTRIC REFLECTOMETRY',
    instrumentType: 'Synthetic Aperture Radar Sounder (15 – 25 MHz Dipole)',
    spectralBand: 'High Frequency Radio (15 MHz – 50 MHz)',
    physicsPrinciple: 'Electromagnetic radar waves penetrate dry regolith and ice, reflecting back when encountering sharp dielectric contrasts like ice-rock or water boundaries.',
    realWorldAnalogs: 'MRO SHARAD, Mars Express MARSIS, Europa Clipper REASON',
    scienceMerit: 'High: The only remote technique capable of peering up to 3 km beneath planetary crusts without physical drilling.',
    dataRate: 'Very High (Raw chirped radar waveforms require significant onboard compression or heavy downlink)',
    operationalComplexity: 'Subject to ionospheric dispersion, surface roughness clutter, and antenna deployment dynamics.',
    supportedObjectives: ['SEARCH_WATER_ICE', 'MAGNETIC_ENVIRONMENT'],
    threeVisualization: 'RADAR_SOUNDING_FAN',
    evidenceLink: 'CASE_05_NAVIGATION',
    phenomenonLink: 'SPACECRAFT_NAVIGATION'
  },
  IN_SITU_MAGNETOMETRY: {
    id: 'IN_SITU_MAGNETOMETRY',
    name: 'FLUXGATE MAGNETOMETER & PLASMA SPECTROMETER',
    kicker: 'DIRECT FIELDS & ENERGETIC PARTICLES',
    instrumentType: 'Dual Triaxial Fluxgate Magnetometer on deployable boom',
    spectralBand: 'DC to 100 Hz magnetic vector field + thermal ion/electron spectrometers',
    physicsPrinciple: 'Lorentz force accelerates ambient charged plasma ions; magnetometer coils measure local magnetic vector induction without optical obscuration.',
    realWorldAnalogs: 'MAVEN MAG/SWEA, Parker Solar Probe FIELDS, Juno MAG',
    scienceMerit: 'Essential for space physics: Directly reconstructs magnetic topology, current sheets, and reconnection zones.',
    dataRate: 'Low to Moderate (1 – 10 kbps continuous field vector sampling)',
    operationalComplexity: 'Spacecraft bus must maintain extreme magnetic cleanliness; requires long boom to isolate from reaction wheels.',
    supportedObjectives: ['MAGNETIC_ENVIRONMENT', 'SOLAR_CORONA_WIND', 'STUDY_ATMOSPHERE'],
    threeVisualization: 'MAGNETIC_FIELD_LINES_AND_BOW_SHOCK',
    evidenceLink: 'CASE_05_NAVIGATION',
    phenomenonLink: 'SPACE_WEATHER'
  },
  MULTISPECTRAL_IMAGING: {
    id: 'MULTISPECTRAL_IMAGING',
    name: 'HIGH-RESOLUTION MULTISPECTRAL POLARIMETRIC IMAGING',
    kicker: 'SPATIAL CONTEXT & MINERALOGICAL MAPPING',
    instrumentType: 'Push-Broom Telescopic Camera with narrow-band filter wheels',
    spectralBand: 'Visible & Shortwave Infrared (0.4 µm – 2.5 µm)',
    physicsPrinciple: 'Reflected sunlight carries distinct diagnostic absorption features of hydrated salts, iron oxides, and ice crystals across spatial pixels.',
    realWorldAnalogs: 'MRO HiRISE / CRISM, LRO LROC, Galileo SSI',
    scienceMerit: 'High: Ground-truth morphology, geological stratigraphy, crater chronology, and volatile frost maps.',
    dataRate: 'Extremely High (Gigabits per swath, requiring selective target downlink prioritization)',
    operationalComplexity: 'Demands tight orbital stability, precise sun-angle illumination, and high onboard storage capacity.',
    supportedObjectives: ['SEARCH_WATER_ICE', 'MAGNETIC_ENVIRONMENT'],
    threeVisualization: 'MULTISPECTRAL_SENSOR_FRUSTUM',
    evidenceLink: 'CASE_04_LOOKBACK_TIME',
    phenomenonLink: 'COSMIC_SCALE'
  },
  ASTROMETRIC_DEFLECTION: {
    id: 'ASTROMETRIC_DEFLECTION',
    name: 'PRECISION ASTROMETRIC INTERFEROMETRY',
    kicker: 'MICRO-ARCSECOND RELATIVISTIC POSITIONAL TRACKING',
    instrumentType: 'Coherent Multi-Telescope Optical / Radio Interferometer Array',
    spectralBand: 'Near-Infrared (2.2 µm) or Millimeter Radio (1.3 mm / 230 GHz)',
    physicsPrinciple: 'Interferometric baseline baseline provides sub-milliarcsecond angular resolution capable of resolving relativistic orbit pericenter shifts.',
    realWorldAnalogs: 'ESO VLTI GRAVITY, Event Horizon Telescope (EHT), Gaia Astrometry',
    scienceMerit: 'Very High: Directly tests General Relativity metric around black holes and probes dark matter halo distribution.',
    dataRate: 'Colossal (Petabytes of raw interferometric correlated data; recorded to disk modules)',
    operationalComplexity: 'Requires sub-wavelength phase coherence across continental baseline distances.',
    supportedObjectives: ['RELATIVISTIC_METRIC'],
    threeVisualization: 'GEODESIC_DEFLECTION_RAYS',
    evidenceLink: 'CASE_03_BLACK_HOLE',
    phenomenonLink: 'GRAVITY_FIELD'
  }
};

export const ARCHITECT_CONSTRAINTS = {
  DISTANCE_LIGHT_TIME: {
    id: 'DISTANCE_LIGHT_TIME',
    label: 'DISTANCE & COMMUNICATIONS LATENCY',
    type: 'derived',
    description: 'Calculated directly from destination astronomical distance using speed of light c = 299,792.458 km/s.'
  },
  DELTA_V_BUDGET: {
    id: 'DELTA_V_BUDGET',
    label: 'PROPULSION DELTA-V ENERGY BUDGET',
    type: 'slider',
    min: 2.5,
    max: 12.0,
    step: 0.5,
    unit: 'km/s',
    default: 4.5,
    description: 'Heliocentric orbital injection and target orbital insertion energy budget (Simplified Hohmann transfer assumption).'
  },
  COMM_BANDWIDTH: {
    id: 'COMM_BANDWIDTH',
    label: 'DOWNLINK FREQUENCY BAND & BANDWIDTH',
    type: 'select',
    options: [
      { id: 'X_BAND_LOW', label: 'X-Band Microwave (8.4 GHz // 32 kbps)', multiplier: 0.4, linkMargin: '+4.2 dB' },
      { id: 'KA_BAND_MED', label: 'Ka-Band Microwave (32 GHz // 250 kbps)', multiplier: 1.0, linkMargin: '+2.8 dB' },
      { id: 'OPTICAL_LASER_HIGH', label: 'Optical Deep Space Laser (1550 nm // 5.0 Mbps)', multiplier: 3.5, linkMargin: '+1.5 dB (Pointing Critical)' }
    ],
    default: 'KA_BAND_MED',
    description: 'Deep Space Network downlink frequency band. Higher bandwidth requires sub-microradian pointing accuracy.'
  },
  THERMAL_POWER: {
    id: 'THERMAL_POWER',
    label: 'PRIMARY POWER & THERMAL REGIME',
    type: 'select',
    options: [
      { id: 'SOLAR_ARRAYS', label: 'High-Efficiency Multi-Junction Solar Array Wings', viability: 'Optimal at ≤ 1.5 AU' },
      { id: 'NUCLEAR_RTG', label: 'Radioisotope Thermoelectric Generator (RTG / Pu-238)', viability: 'Essential at ≥ 3.0 AU or shadow' },
      { id: 'HIGH_THERMAL_SHIELD', label: 'Carbon-Carbon Thermal Ablative Shield + Active Cooling', viability: 'Required at ≤ 0.2 AU' }
    ],
    default: 'SOLAR_ARRAYS',
    description: 'Power source and environmental thermal conditioning.'
  }
};

/**
 * Trade-Off Rules Engine:
 * Generates transparent scientific trade-offs rather than game scores.
 */
export function evaluateMissionTradeOffs(targetId, objectiveId, methodId, constraints = {}) {
  const target = ARCHITECT_TARGETS[targetId];
  const objective = ARCHITECT_OBJECTIVES[objectiveId];
  const method = ARCHITECT_METHODS[methodId];

  if (!target || !objective || !method) {
    return null;
  }

  // Check scientific validity
  const isTargetSupported = objective.validTargets.includes(targetId);
  const isMethodSupported = objective.compatibleMethods.includes(methodId);
  const isScientificallyValid = isTargetSupported && isMethodSupported;

  // Compute qualitative metrics (0-100 scale for UI bars, clearly labeled as qualitative)
  let scienceValue = 82;
  let dataComplexity = 60;
  let commChallenge = 50;
  let observationComplexity = 65;

  // Target distance factors into communication challenge
  if (target.distanceAU > 1000) {
    commChallenge = 98; // interstellar / galactic
  } else if (target.distanceAU > 3.0) {
    commChallenge = 85; // outer solar system
  } else if (target.distanceAU > 1.2) {
    commChallenge = 65; // Mars
  } else if (targetId === 'MOON') {
    commChallenge = 20; // Lunar
  } else {
    commChallenge = 10;
  }

  // Method data complexity
  if (methodId === 'MULTISPECTRAL_IMAGING' || methodId === 'ASTROMETRIC_DEFLECTION') {
    dataComplexity = 95;
    scienceValue += 8;
  } else if (methodId === 'RADAR_SOUNDING' || methodId === 'SPECTROSCOPY_HIGH_RES') {
    dataComplexity = 78;
    scienceValue += 6;
  } else if (methodId === 'TRANSIT_PHOTOMETRY') {
    dataComplexity = 55;
    scienceValue += 5;
  } else {
    dataComplexity = 35; // Magnetometry
  }

  // Observation complexity
  if (targetId === 'PARKER_SUN' || targetId === 'SAGITTARIUS_A') {
    observationComplexity = 95;
  } else if (targetId === 'TRAPPIST_1E') {
    observationComplexity = 90;
  } else if (methodId === 'RADAR_SOUNDING') {
    observationComplexity = 70;
  }

  // Power constraint viability check
  let powerAdvisory = 'Power architecture aligns with destination solar flux.';
  const selectedPower = constraints.thermalPower || 'SOLAR_ARRAYS';
  if ((targetId === 'EUROPA' || targetId === 'TRAPPIST_1E' || targetId === 'SAGITTARIUS_A') && selectedPower === 'SOLAR_ARRAYS') {
    powerAdvisory = 'CAUTION: Target distance exhibits severely diminished solar flux (<50 W/m²). Large solar panels provide insufficient wattage; an RTG or nuclear fission power source is recommended.';
  } else if (targetId === 'PARKER_SUN' && selectedPower !== 'HIGH_THERMAL_SHIELD') {
    powerAdvisory = 'CRITICAL: Perihelion thermal flux exceeds 650 kW/m². A carbon-carbon heat shield and active fluid cooling loop are mandatory to prevent spacecraft vaporization.';
  }

  // Derive concrete Trade-offs
  const tradeOffs = {
    isValid: isScientificallyValid,
    invalidationReason: !isTargetSupported 
      ? `Target ${target.name} does not possess physical environments suitable for ${objective.name}.`
      : !isMethodSupported
      ? `Observation method ${method.name} is not appropriate for observing ${objective.name}.`
      : null,
    metrics: {
      scienceValue: Math.min(100, Math.max(20, scienceValue)),
      dataComplexity: Math.min(100, Math.max(20, dataComplexity)),
      commChallenge: Math.min(100, Math.max(20, commChallenge)),
      observationComplexity: Math.min(100, Math.max(20, observationComplexity))
    },
    advantage: getTradeOffAdvantage(targetId, objectiveId, methodId),
    limitation: getTradeOffLimitation(targetId, objectiveId, methodId),
    dependency: getTradeOffDependency(targetId, objectiveId, methodId),
    openQuestion: getTradeOffOpenQuestion(targetId, objectiveId, methodId),
    powerAdvisory,
    integrityChecklist: [
      {
        criterion: 'SOURCE VERIFIED',
        status: 'VERIFIED',
        detail: `Grounded in ${target.source} and ${objective.source}.`
      },
      {
        criterion: 'OBSERVATION METHOD APPROPRIATE',
        status: isMethodSupported ? 'VERIFIED' : 'UNKNOWN',
        detail: isMethodSupported 
          ? `${method.name} directly detects ${objective.keyScientificMetric}.`
          : `Method cannot resolve target diagnostic metrics.`
      },
      {
        criterion: 'TARGET SUPPORTED',
        status: isTargetSupported ? 'VERIFIED' : 'UNKNOWN',
        detail: isTargetSupported
          ? `Empirical physical parameters cataloged in application database.`
          : `Target does not possess the physical conditions needed for this objective.`
      },
      {
        criterion: 'ASSUMPTIONS DECLARED',
        status: 'SIMPLIFIED',
        detail: 'Orbital transfer and instrument integration rely on simplified educational models.'
      },
      {
        criterion: 'LIMITATIONS DISCLOSED',
        status: 'SUPPORTED',
        detail: 'Trade-off engine explicitly declares observation gaps and physical uncertainties.'
      }
    ]
  };

  return tradeOffs;
}

function getTradeOffAdvantage(targetId, objectiveId, methodId) {
  if (methodId === 'SPECTROSCOPY_HIGH_RES') {
    return 'Provides unambiguous chemical identification via quantized molecular absorption lines, establishing definite elemental inventories.';
  } else if (methodId === 'TRANSIT_PHOTOMETRY') {
    return 'Delivers sub-percent planetary radius measurements and atmospheric scale heights without requiring extreme spatial resolution.';
  } else if (methodId === 'RADAR_SOUNDING') {
    return 'Directly penetrates opaque dust, surface regolith, and ice shells to reveal dielectric stratigraphy unreachable by optical instruments.';
  } else if (methodId === 'IN_SITU_MAGNETOMETRY') {
    return 'Continuously records vector magnetic fields and thermal plasma populations in-situ, unhampered by line-of-sight dust absorption.';
  } else if (methodId === 'MULTISPECTRAL_IMAGING') {
    return 'Creates continuous spatial maps correlating surface morphology with mineralogical absorption features across broad planetary swaths.';
  } else if (methodId === 'ASTROMETRIC_DEFLECTION') {
    return 'Achieves micro-arcsecond astrometric precision, directly revealing general relativistic geodesic curvature in strong-field gravity.';
  }
  return 'Delivers direct observational constraints on physical target parameters.';
}

function getTradeOffLimitation(targetId, objectiveId, methodId) {
  if (methodId === 'SPECTROSCOPY_HIGH_RES') {
    return 'Opaque high-altitude aerosols, photochemical hazes, or dense cloud decks can mask underlying atmospheric layers and surface features.';
  } else if (methodId === 'TRANSIT_PHOTOMETRY') {
    return 'Restricted strictly to edge-on orbital geometries (inclination i ≈ 90°); provides no information on surface morphology or geological context.';
  } else if (methodId === 'RADAR_SOUNDING') {
    return 'Cannot detect trace chemical species; surface clutter and rough topography can generate ghost reflections that mimic subsurface interfaces.';
  } else if (methodId === 'IN_SITU_MAGNETOMETRY') {
    return 'Provides only single-point measurement along the spacecraft trajectory; spatial interpolation requires multi-point constellation or modeling.';
  } else if (methodId === 'MULTISPECTRAL_IMAGING') {
    return 'Generates extreme data volumes that strain deep-space downlink bandwidth; sensitive only to the optical skin depth (<1 mm) of the surface.';
  } else if (methodId === 'ASTROMETRIC_DEFLECTION') {
    return 'Requires long integration baselines; vulnerable to telescope thermal drift and background star crowding in dense galactic fields.';
  }
  return 'Subject to instrument sensitivity thresholds and observational geometry constraints.';
}

function getTradeOffDependency(targetId, objectiveId, methodId) {
  if (targetId === 'TRAPPIST_1E' || targetId === 'SAGITTARIUS_A') {
    return 'Depends on long-baseline deep space tracking and Earth-based synchronized observatory networks (JWST, EHT, VLT).';
  } else if (targetId === 'EUROPA') {
    return 'Requires nuclear RTG power conditioning and radiation-hardened electronics to survive Jupiter’s intense Jovian trapped radiation belt.';
  } else if (targetId === 'PARKER_SUN') {
    return 'Depends on continuous autonomous attitude control to keep sensitive payload strictly within the shadow cone of the carbon heat shield.';
  } else if (targetId === 'MARS') {
    return 'Relies on Deep Space Network (DSN) 70-meter dish scheduling and autonomous onboard fault protection due to the 25-minute round-trip light lag.';
  }
  return 'Requires synchronized ground tracking, reliable power conditioning, and calibrated reference starfields.';
}

function getTradeOffOpenQuestion(targetId, objectiveId, methodId) {
  if (objectiveId === 'SEARCH_WATER_ICE') {
    return 'Are detected dielectric anomalies pure water ice deposits, or porous basaltic regolith saturated with hypersaline brines or CO2 dry ice clathrates?';
  } else if (objectiveId === 'EXOPLANET_BIOSIGNATURE') {
    return 'Could detected methane and ozone be sustained by abiotic serpentinization and ultraviolet photolysis of water vapor rather than active biology?';
  } else if (objectiveId === 'STUDY_ATMOSPHERE') {
    return 'What fraction of historical planetary atmosphere was stripped by solar wind sputtering versus swallowed by crustal hydration reactions?';
  } else if (objectiveId === 'MAGNETIC_ENVIRONMENT') {
    return 'How rapidly does the dayside magnetopause compress during extreme Carrington-class coronal mass ejection impacts?';
  } else if (objectiveId === 'RELATIVISTIC_METRIC') {
    return 'Does spacetime near the event horizon conform strictly to the vacuum Kerr metric, or are quantum hair/fuzzball deviations present?';
  } else if (objectiveId === 'SOLAR_CORONA_WIND') {
    return 'Do switchbacks originate deep in solar magnetic funnels or develop higher in the expanding heliospheric solar wind?';
  }
  return 'What unmodeled physical processes could introduce systematic biases into the empirical dataset?';
}
