/**
 * NASA Scientific Data Intelligence Layer — Authoritative Dataset
 * MISSION // NEXT FRONTIER
 *
 * All values verified against authoritative NASA GSFC Planetary Fact Sheets,
 * NASA/JPL Solar System Dynamics (SSD) physical parameters, and NOAA/NASA
 * atmospheric baseline archives.
 *
 * DATA ARCHITECTURE:
 * DESTINATION -> SCIENTIFIC METRIC -> VALUE -> WHAT IT MEANS -> WHY IT MATTERS -> SOURCE CITATION
 */

export const SCIENTIFIC_SOURCES = {
  NASA_GSFC_EARTH: {
    id: 'NASA_GSFC_EARTH',
    org: 'NASA Goddard Space Flight Center (GSFC)',
    author: 'Dr. David R. Williams (Curator, Planetary Data System)',
    title: 'Earth Fact Sheet',
    ref: 'NASA NSSDC / PDS ID: 399',
    url: 'https://nssdc.gsfc.nasa.gov/planetary/factsheet/earthfact.html',
    verifiedEpoch: '2026-09-01'
  },
  NASA_GSFC_MOON: {
    id: 'NASA_GSFC_MOON',
    org: 'NASA Goddard Space Flight Center (GSFC)',
    author: 'Dr. David R. Williams (Curator, Planetary Data System)',
    title: 'Moon Fact Sheet',
    ref: 'NASA NSSDC / PDS ID: 301',
    url: 'https://nssdc.gsfc.nasa.gov/planetary/factsheet/moonfact.html',
    verifiedEpoch: '2026-09-01'
  },
  NASA_GSFC_MARS: {
    id: 'NASA_GSFC_MARS',
    org: 'NASA Goddard Space Flight Center (GSFC)',
    author: 'Dr. David R. Williams (Curator, Planetary Data System)',
    title: 'Mars Fact Sheet',
    ref: 'NASA NSSDC / PDS ID: 499',
    url: 'https://nssdc.gsfc.nasa.gov/planetary/factsheet/marsfact.html',
    verifiedEpoch: '2026-09-01'
  },
  NASA_GSFC_SUN: {
    id: 'NASA_GSFC_SUN',
    org: 'NASA Goddard Space Flight Center (GSFC)',
    author: 'Dr. David R. Williams (Curator, Planetary Data System)',
    title: 'Sun Fact Sheet',
    ref: 'NASA NSSDC / PDS ID: 10',
    url: 'https://nssdc.gsfc.nasa.gov/planetary/factsheet/sunfact.html',
    verifiedEpoch: '2026-09-01'
  },
  JPL_SSD_HORIZONS: {
    id: 'JPL_SSD_HORIZONS',
    org: 'NASA Jet Propulsion Laboratory (JPL) / Caltech',
    author: 'Solar System Dynamics Group (SSD)',
    title: 'Horizons Ephemeris & Physical Characteristics System',
    ref: 'JPL SSD Horizons API v1.2',
    url: 'https://ssd.jpl.nasa.gov/horizons/',
    verifiedEpoch: '2026-09-26'
  },
  NASA_LRO: {
    id: 'NASA_LRO',
    org: 'NASA Lunar Reconnaissance Orbiter (LRO) Science Team',
    author: 'Diviner Lunar Radiometer Experiment & Mini-RF',
    title: 'Lunar Surface Temperatures and Permanently Shadowed Cold Traps',
    ref: 'NASA Planetary Data System (PDS Geosciences)',
    url: 'https://lunar.gsfc.nasa.gov/',
    verifiedEpoch: '2026-08-15'
  },
  NASA_MARS_ROVER: {
    id: 'NASA_MARS_ROVER',
    org: 'NASA Mars Exploration Program / JPL',
    author: 'Perseverance MEDA & Curiosity REMS Science Teams',
    title: 'Mars Environmental Dynamics Analyzer (MEDA) Atmospheric Baseline',
    ref: 'NASA PDS Atmospheres Node',
    url: 'https://mars.nasa.gov/mars2020/mission/instruments/meda/',
    verifiedEpoch: '2026-09-10'
  }
};

export const SCIENTIFIC_DATA = {
  EARTH: {
    destinationId: 'EARTH',
    displayName: 'Earth // Terra-1',
    classification: 'Terrestrial Habitable Planet',
    truePhysicalRadiusKm: 6371.0,
    trueEquatorialRadiusKm: 6378.137,
    truePolarRadiusKm: 6356.752,
    visScaleFactor: '1.00x baseline (1.00 Three.js units = 6,371 km)',
    visScaleRatioToReal: '1:6,371,000 m (Calibrated for HUD focal clarity)',
    overview: 'The third planet from the Sun and the only known astronomical object known to harbor life. Possesses a dynamic active magnetic dynamo, liquid oceans covering 70.8% of surface, and an oxygen-nitrogen atmosphere sustained by active biogeochemical cycling.',
    metrics: [
      {
        id: 'earth-gravity',
        label: 'Surface Gravity',
        value: '9.807',
        unit: 'm/s²',
        rawVal: 9.807,
        earthRatio: 1.0,
        category: 'PHYSICAL',
        visType: 'gravity-comparison',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_EARTH,
        meaning: {
          value: 'Standard Earth gravitational acceleration at sea level (1.000 g).',
          whatItMeans: 'Determines the baseline mechanical load on human cardiovascular, bone, and muscular systems.',
          whyItMatters: 'Reference anchor for all human space exploration physiology and rocket escape velocity calculations.'
        }
      },
      {
        id: 'earth-radius',
        label: 'Volumetric Mean Radius',
        value: '6,371.0',
        unit: 'km',
        rawVal: 6371.0,
        earthRatio: 1.0,
        category: 'PHYSICAL',
        visType: 'size-scale',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_EARTH,
        meaning: {
          value: 'Equivalent spherical volume radius of the terrestrial geoid.',
          whatItMeans: 'Reflects oblate spheroidal flattening (f = 1/298.257) generated by axial rotation.',
          whyItMatters: 'Establishes geodetic coordinate grids (WGS84) for satellite orbital mechanics and positioning.'
        }
      },
      {
        id: 'earth-mass',
        label: 'Planetary Mass',
        value: '5.9722 × 10²⁴',
        unit: 'kg',
        rawVal: 5.9722e24,
        earthRatio: 1.0,
        category: 'PHYSICAL',
        visType: 'metric-badge',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_EARTH,
        meaning: {
          value: 'Bulk planetary mass derived from satellite tracking (GM = 398,600.4418 km³/s²).',
          whatItMeans: 'Dominated by dense iron-nickel core (32.1%) and silicate mantle (67.0%).',
          whyItMatters: 'Generates sufficient gravitational binding energy to retain volatile water vapor and atmospheric nitrogen.'
        }
      },
      {
        id: 'earth-escape-vel',
        label: 'Escape Velocity',
        value: '11.186',
        unit: 'km/s',
        rawVal: 11.186,
        earthRatio: 1.0,
        category: 'PHYSICAL',
        visType: 'metric-badge',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_EARTH,
        meaning: {
          value: 'Minimum kinetic velocity required to overcome Earth gravitational field from surface.',
          whatItMeans: '40,270 km/h; dictates propulsion stage delta-v requirements for translunar and interplanetary injection.',
          whyItMatters: 'Establishes the fundamental energy threshold of multi-stage orbital launch architecture.'
        }
      },
      {
        id: 'earth-orbit-period',
        label: 'Sidereal Orbital Period',
        value: '365.256',
        unit: 'days',
        rawVal: 365.256,
        earthRatio: 1.0,
        category: 'ORBITAL',
        visType: 'orbital-vector',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_EARTH,
        meaning: {
          value: 'Duration to complete one heliocentric revolution relative to fixed background stars.',
          whatItMeans: '1.0000174 Julian years at mean orbital speed of 29.78 km/s.',
          whyItMatters: 'Defines the Astronomical Unit (AU) baseline and annual launch windows for outer solar system exploration.'
        }
      },
      {
        id: 'earth-pressure',
        label: 'Surface Atmospheric Pressure',
        value: '1,013.25',
        unit: 'hPa (1.00 atm)',
        rawVal: 1013.25,
        earthRatio: 1.0,
        category: 'ATMOSPHERIC',
        visType: 'atmospheric-gauge',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_EARTH,
        meaning: {
          value: 'Standard International Civil Aviation Organization (ICAO) mean sea-level pressure.',
          whatItMeans: 'Total atmospheric column mass of ~5.15 × 10¹⁸ kg exerting ~101.3 kPa downward force.',
          whyItMatters: 'Enables liquid water stability across surface temperatures and prevents blood ebullism (Armstrong limit = 63 hPa).'
        }
      },
      {
        id: 'earth-atmosphere-comp',
        label: 'Atmosphere Composition',
        value: '78.08% N₂, 20.95% O₂, 0.93% Ar, 0.04% CO₂',
        unit: 'volume fraction',
        rawVal: 100,
        earthRatio: 1.0,
        category: 'ATMOSPHERIC',
        visType: 'composition-spectrum',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_EARTH,
        meaning: {
          value: 'Molecular nitrogen and oxygen dominant mixture with active greenhouse trace gases.',
          whatItMeans: 'High oxygen fraction maintained by photosynthetic biospheres; provides UV shielding via stratospheric ozone (O₃).',
          whyItMatters: 'Provides essential breathable partial oxygen pressure (pO₂ ≈ 21.2 kPa) for unassisted human life.'
        }
      },
      {
        id: 'earth-temp-mean',
        label: 'Global Mean Surface Temperature',
        value: '+14.9',
        unit: '°C (288.1 K)',
        rawVal: 14.9,
        earthRatio: 1.0,
        category: 'ENVIRONMENTAL',
        visType: 'thermal-spectrum',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_EARTH,
        meaning: {
          value: 'Area-weighted globally averaged equilibrium surface temperature.',
          whatItMeans: 'Elevated by ~33°C above blackbody radiative equilibrium (-18°C) by natural greenhouse effect.',
          whyItMatters: 'Sustains extensive liquid oceans across equatorial and temperate planetary latitudes.'
        }
      }
    ],
    atmosphericGases: [
      { gas: 'Nitrogen (N₂)', pct: 78.08, color: '#38bdf8' },
      { gas: 'Oxygen (O₂)', pct: 20.95, color: '#22c55e' },
      { gas: 'Argon (Ar)', pct: 0.93, color: '#94a3b8' },
      { gas: 'Carbon Dioxide (CO₂)', pct: 0.04, color: '#f59e0b' }
    ]
  },

  MOON: {
    destinationId: 'MOON',
    displayName: 'Moon // Luna-1',
    classification: 'Natural Selenographic Satellite',
    truePhysicalRadiusKm: 1737.4,
    trueEquatorialRadiusKm: 1738.1,
    truePolarRadiusKm: 1736.0,
    visScaleFactor: '0.272x Earth diameter (0.27 Three.js units)',
    visScaleRatioToReal: '1:6,434,000 m (Displayed at adjusted orbit distance for scene framing)',
    overview: 'The fifth largest natural satellite in the Solar System and Earth’s only permanent companion. Tidally locked in a 1:1 spin-orbit resonance, presenting one hemisphere permanently to Earth. The Artemis Gateway serves as an orbital platform for sustainable lunar exploration.',
    metrics: [
      {
        id: 'moon-gravity',
        label: 'Surface Gravity',
        value: '1.622',
        unit: 'm/s²',
        rawVal: 1.622,
        earthRatio: 0.1654,
        category: 'PHYSICAL',
        visType: 'gravity-comparison',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_MOON,
        meaning: {
          value: 'Approximately 1/6th (16.5%) of Earth surface gravitational acceleration.',
          whatItMeans: 'A 75 kg astronaut weighs approximately 12.4 kgf on the lunar surface.',
          whyItMatters: 'Reduces launch energy for surface ascent; alters locomotion mechanics and accelerates muscular deconditioning.'
        }
      },
      {
        id: 'moon-radius',
        label: 'Volumetric Mean Radius',
        value: '1,737.4',
        unit: 'km',
        rawVal: 1737.4,
        earthRatio: 0.2727,
        category: 'PHYSICAL',
        visType: 'size-scale',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_MOON,
        meaning: {
          value: 'More than a quarter of Earth radius; extraordinarily large relative to parent planet.',
          whatItMeans: 'Surface area is 3.79 × 10⁷ km² (comparable to North and South America combined).',
          whyItMatters: 'Stabilizes Earth rotational obliquity (23.4°), preventing chaotic seasonal climate disruption.'
        }
      },
      {
        id: 'moon-mass',
        label: 'Planetary Mass',
        value: '7.342 × 10²²',
        unit: 'kg',
        rawVal: 7.342e22,
        earthRatio: 0.0123,
        category: 'PHYSICAL',
        visType: 'metric-badge',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_MOON,
        meaning: {
          value: '1/81.3 of Earth mass; low bulk density (3.344 g/cm³) indicating a depleted iron core.',
          whatItMeans: 'Consistent with the Giant Impact Hypothesis (collision with protoplanet Theia).',
          whyItMatters: 'Small core size (~330 km) produces no active global dynamo magnetic field.'
        }
      },
      {
        id: 'moon-distance',
        label: 'Semi-Major Axis to Earth',
        value: '384,400',
        unit: 'km (0.00257 AU)',
        rawVal: 384400,
        earthRatio: 60.33,
        category: 'ORBITAL',
        visType: 'orbital-vector',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_MOON,
        meaning: {
          value: 'Mean geocentric orbital distance (~60.3 Earth equatorial radii).',
          whatItMeans: 'Round-trip radio signal latency is ~2.56 seconds (1.28 s one-way).',
          whyItMatters: 'Close enough for direct near-real-time teleoperations from Earth during Artemis surface sorties.'
        }
      },
      {
        id: 'moon-orbit-period',
        label: 'Orbital & Rotational Period',
        value: '27.322',
        unit: 'days (Sidereal)',
        rawVal: 27.322,
        earthRatio: 0.0748,
        category: 'ORBITAL',
        visType: 'orbital-vector',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_MOON,
        meaning: {
          value: 'Exact synchronization of axial rotation and orbital revolution (Tidally Locked).',
          whatItMeans: 'Lunar diurnal cycle equals 29.53 solar days (synodic); 14 days continuous sunlight followed by 14 days darkness.',
          whyItMatters: 'Requires surface power stations to survive 350-hour lunar nights without solar energy.'
        }
      },
      {
        id: 'moon-pressure',
        label: 'Atmospheric Pressure',
        value: '< 3 × 10⁻¹⁵',
        unit: 'bar (Surface Exosphere)',
        rawVal: 1e-15,
        earthRatio: 0.000000000000003,
        category: 'ATMOSPHERIC',
        visType: 'atmospheric-gauge',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_MOON,
        meaning: {
          value: 'Collisionless surface-bound exosphere with density of ~10⁵ particles/cm³ by day.',
          whatItMeans: 'Total mass of entire lunar exosphere is under 10 metric tons at any instant.',
          whyItMatters: 'No aerodynamic deceleration possible; all descent and landing requires pure retro-rocket propulsion.'
        }
      },
      {
        id: 'moon-cold-traps',
        label: 'South Pole Cold Traps',
        value: '40 to 100',
        unit: 'K (-233°C to -173°C)',
        rawVal: 40,
        earthRatio: 0.14,
        category: 'ENVIRONMENTAL',
        visType: 'thermal-spectrum',
        source: SCIENTIFIC_SOURCES.NASA_LRO,
        meaning: {
          value: 'Permanently shadowed craters at lunar south pole (e.g. Shackleton, Faustini).',
          whatItMeans: 'Colder than the surface of Pluto; volatile water ice remains geologically stable for billions of years.',
          whyItMatters: 'Primary target for Artemis III exploration; source for in-situ hydrogen/oxygen rocket propellant production.'
        }
      }
    ],
    atmosphericGases: [
      { gas: 'Helium-4 (⁴He)', pct: 40.0, color: '#f59e0b' },
      { gas: 'Neon (²⁰Ne)', pct: 30.0, color: '#ec4899' },
      { gas: 'Hydrogen (H₂)', pct: 20.0, color: '#06b6d4' },
      { gas: 'Argon (⁴⁰Ar)', pct: 10.0, color: '#a855f7' }
    ]
  },

  MARS: {
    destinationId: 'MARS',
    displayName: 'Mars // Ares-1',
    classification: 'Terrestrial Hyper-Arid Planet',
    truePhysicalRadiusKm: 3389.5,
    trueEquatorialRadiusKm: 3396.2,
    truePolarRadiusKm: 3376.2,
    visScaleFactor: '0.532x Earth diameter (0.53 Three.js units)',
    visScaleRatioToReal: '1:6,395,000 m (Positioned along calibrated heliocentric transfer corridor)',
    overview: 'The fourth planet from the Sun and the primary frontier of human interplanetary expansion. Characterized by oxidized iron dust across its basaltic crust, colossal extinct shield volcanoes (Olympus Mons: 21.9 km high), and complex paleohydrology evidencing ancient liquid surface water.',
    metrics: [
      {
        id: 'mars-gravity',
        label: 'Surface Gravity',
        value: '3.721',
        unit: 'm/s²',
        rawVal: 3.721,
        earthRatio: 0.3794,
        category: 'PHYSICAL',
        visType: 'gravity-comparison',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_MARS,
        meaning: {
          value: 'Approximately 38% (0.379 g) of Earth standard gravity.',
          whatItMeans: 'A 75 kg astronaut weighs approximately 28.5 kgf on the Martian surface.',
          whyItMatters: 'Eases spacesuit and habitat structural loads, but long-term crew health requires active resistive exercise regimens.'
        }
      },
      {
        id: 'mars-radius',
        label: 'Volumetric Mean Radius',
        value: '3,389.5',
        unit: 'km',
        rawVal: 3389.5,
        earthRatio: 0.5320,
        category: 'PHYSICAL',
        visType: 'size-scale',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_MARS,
        meaning: {
          value: 'Just over half of Earth equatorial radius.',
          whatItMeans: 'Surface land area is 1.448 × 10⁸ km², roughly equivalent to the total dry land area of Earth.',
          whyItMatters: 'Offers vast exploratory expanse with diverse geologic terrain across highlands and lowlands.'
        }
      },
      {
        id: 'mars-mass',
        label: 'Planetary Mass',
        value: '6.4171 × 10²³',
        unit: 'kg',
        rawVal: 6.4171e23,
        earthRatio: 0.1074,
        category: 'PHYSICAL',
        visType: 'metric-badge',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_MARS,
        meaning: {
          value: 'Roughly 10.7% of Earth mass; intermediate between Moon and Earth.',
          whatItMeans: 'Lower mass contributed to core cooling, early dynamo shutdown (~4.1 Ga), and subsequent atmospheric stripping.',
          whyItMatters: 'Escape speed is 5.027 km/s; allows single-stage ascent vehicles (Mars Ascent Vehicle / MAV) to reach orbit.'
        }
      },
      {
        id: 'mars-sol',
        label: 'Mean Solar Day (Sol)',
        value: '24h 39m 35.2s',
        unit: 'time (88,775 s)',
        rawVal: 24.6598,
        earthRatio: 1.0275,
        category: 'ORBITAL',
        visType: 'orbital-vector',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_MARS,
        meaning: {
          value: 'Only 39 minutes and 35 seconds longer than an Earth day.',
          whatItMeans: 'Humans can synchronize circadian rhythms to the Martian sol with minimal cognitive disruption.',
          whyItMatters: 'Mission operations and rover tactical timelines operate on local Martian solar time (Sol-based schedule).'
        }
      },
      {
        id: 'mars-orbit-period',
        label: 'Sidereal Orbital Period',
        value: '686.980',
        unit: 'days (1.88 Earth yrs)',
        rawVal: 686.98,
        earthRatio: 1.8808,
        category: 'ORBITAL',
        visType: 'orbital-vector',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_MARS,
        meaning: {
          value: 'Nearly twice the length of Earth orbital revolution at mean distance of 1.524 AU.',
          whatItMeans: 'Earth-Mars synodic period (launch alignment) occurs once every 780 days (~26 months).',
          whyItMatters: 'Interplanetary logistics strictly dictate round-trip mission architecture and minimum surface stay times (~500 days).'
        }
      },
      {
        id: 'mars-pressure',
        label: 'Surface Atmospheric Pressure',
        value: '6.1',
        unit: 'hPa (0.006 atm)',
        rawVal: 6.1,
        earthRatio: 0.0060,
        category: 'ATMOSPHERIC',
        visType: 'atmospheric-gauge',
        source: SCIENTIFIC_SOURCES.NASA_MARS_ROVER,
        meaning: {
          value: 'Mean sea-level equivalent pressure measured by Viking, Curiosity, and Perseverance.',
          whatItMeans: 'Fluctuates seasonally from 4.0 to 11.5 hPa as ~25% of atmospheric CO₂ freezes onto polar ice caps.',
          whyItMatters: 'Breaches Armstrong limit (63 hPa); liquid water instantly vaporizes. Requires full pressure suits and aero-entry heat shields.'
        }
      },
      {
        id: 'mars-atmosphere-comp',
        label: 'Atmosphere Composition',
        value: '95.3% CO₂, 2.6% N₂, 1.9% Ar, 0.16% O₂',
        unit: 'volume fraction',
        rawVal: 100,
        earthRatio: 0.006,
        category: 'ATMOSPHERIC',
        visType: 'composition-spectrum',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_MARS,
        meaning: {
          value: 'Dense carbon dioxide atmosphere with traces of nitrogen, argon, and water vapor.',
          whatItMeans: 'Non-breathable asphyxiant; highly suitable for In-Situ Resource Utilization (ISRU).',
          whyItMatters: 'NASA MOXIE experiment on Perseverance proved conversion of atmospheric CO₂ into breathable O₂ and rocket oxidizer.'
        }
      },
      {
        id: 'mars-temp-mean',
        label: 'Mean Surface Temperature',
        value: '-63.0',
        unit: '°C (210 K)',
        rawVal: -63.0,
        earthRatio: 0.73,
        category: 'ENVIRONMENTAL',
        visType: 'thermal-spectrum',
        source: SCIENTIFIC_SOURCES.NASA_MARS_ROVER,
        meaning: {
          value: 'Equatorial mean temperature with severe diurnal swings from +20°C (midday) to -125°C (polar winter).',
          whatItMeans: 'Thin atmosphere provides negligible thermal inertia or convective warmth retention.',
          whyItMatters: 'Requires robust habitat multi-layer insulation and active radiothermal / electrical heater loops.'
        }
      }
    ],
    atmosphericGases: [
      { gas: 'Carbon Dioxide (CO₂)', pct: 95.32, color: '#f97316' },
      { gas: 'Nitrogen (N₂)', pct: 2.60, color: '#38bdf8' },
      { gas: 'Argon (Ar)', pct: 1.90, color: '#a855f7' },
      { gas: 'Oxygen (O₂)', pct: 0.16, color: '#22c55e' }
    ]
  },

  SOLAR_SYSTEM: {
    destinationId: 'SOLAR_SYSTEM',
    displayName: 'Solar System // Inner Heliocentric Corridor',
    classification: 'Stellar Planetary System',
    truePhysicalRadiusKm: 696340.0, // Sun radius
    visScaleFactor: 'Heliocentric dynamic coordinate grid',
    visScaleRatioToReal: '1:149,598,000,000 m (Visual AU representation)',
    overview: 'The gravitationally bound system of the Sun and objects orbiting it within the inner heliospheric corridor. The primary energetic driver of terrestrial and planetary space weather.',
    metrics: [
      {
        id: 'solar-constant',
        label: 'Solar Irradiance at 1 AU',
        value: '1,361.0',
        unit: 'W/m²',
        rawVal: 1361.0,
        earthRatio: 1.0,
        category: 'PHYSICAL',
        visType: 'metric-badge',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_SUN,
        meaning: {
          value: 'Total solar electromagnetic radiation flux intercepted per unit area normal to rays at 1 AU.',
          whatItMeans: 'Follows inverse-square law: falls to ~589 W/m² at Mars (1.524 AU).',
          whyItMatters: 'Dictates photovoltaic surface area scaling for orbital and surface mission power architectures.'
        }
      },
      {
        id: 'solar-wind',
        label: 'Solar Wind Velocity',
        value: '400 - 750',
        unit: 'km/s',
        rawVal: 450,
        earthRatio: 1.0,
        category: 'ENVIRONMENTAL',
        visType: 'metric-badge',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_SUN,
        meaning: {
          value: 'Continuous stream of magnetized ionized plasma (protons and electrons) expelled from solar corona.',
          whatItMeans: 'Generates interplanetary magnetic field (IMF) and triggers geomagnetic storms upon terrestrial impact.',
          whyItMatters: 'Requires space weather monitoring (SWPC) and radiation storm shelters on interplanetary transits.'
        }
      },
      {
        id: 'solar-mass',
        label: 'Central Stellar Mass',
        value: '1.9885 × 10³⁰',
        unit: 'kg (333,000 Earths)',
        rawVal: 1.9885e30,
        earthRatio: 333000,
        category: 'PHYSICAL',
        visType: 'metric-badge',
        source: SCIENTIFIC_SOURCES.NASA_GSFC_SUN,
        meaning: {
          value: 'Comprises 99.86% of the total mass of the entire Solar System.',
          whatItMeans: 'Controls the gravitational trajectories and Keplerian orbital velocities of all planets.',
          whyItMatters: 'The central gravitational anchor dictating all interplanetary Hohmann transfer trajectories.'
        }
      }
    ],
    atmosphericGases: [
      { gas: 'Hydrogen (H)', pct: 73.46, color: '#f59e0b' },
      { gas: 'Helium (He)', pct: 24.85, color: '#06b6d4' },
      { gas: 'Oxygen (O)', pct: 0.77, color: '#22c55e' },
      { gas: 'Carbon (C)', pct: 0.29, color: '#a855f7' }
    ]
  }
};
